
# Ingredient.create(name: "lemon")
# Ingredient.create(name: "vodka")
# Ingredient.create(name: "lime")
# Ingredient.create(name: "cucumber")
# Ingredient.create(name: "triple sec")
# Ingredient.create(name: "")
# Ingredient.create(name: "whiskey")
# Ingredient.create(name: "ginger beer")
# Ingredient.create(name: "rum")
# Ingredient.create(name: "gin")
# Ingredient.create(name: "ice")
# Ingredient.create(name: "tonic water")
